- scripts/deploy.sh
- scripts/load_kidsfirst.sh
- smilecdr/Dockerfile
- smilecdr/classes/cdr-config-Master.properties
- smilecdr/docker-compose-basic.yml
- smilecdr/docker-compose.yml
> 🔧 Refactor Docker Stack + Validation On

- README.md
- requirements.txt
- scripts/config.py
- scripts/deploy.sh
- scripts/load_settings.py
- scripts/merge_properties.py
- scripts/users.py
- scripts/utils.py
- smilecdr/classes/cdr-config-Master.properties
- smilecdr/classes/logback.xml
- smilecdr/docker-compose.yml
In support of https://github.com/d3b-center/clinical-data-flow/issues/25
Closes #11, #13, #12, #15
> ⚡️Upgrade SmileCDR, add server scripts, enable search features 

- README.md
- scripts/deploy.sh
Fix handling of docker image in deploy script and fix developer instruction in readme.
> 🐛 Fix deploy script

- .gitignore
- smilecdr/bin/setenv
- smilecdr/docker-compose.yml
Forgot to push these commits up. Deployed dev server already has heap memory increased.
> 🔧 Increase heap memory to 2x

- scripts/deploy.sh
- smilecdr/docker-compose.yml
> 🐳 Bump to docker img with $snapshot endpoint fix

- README.md
- smilecdr/docker-compose.yml
Closes #29 
FYI for Reviewers:
**Dashboard has already been deployed at `http://10.10.1.141`**
> 🐳 Add dashboard to docker-compose stack

- .circleci/config.yml
> 👷 Add CirclCI to test deploy

- server/postgres/Dockerfile
> Pin to Postgres 11.4

- Dockerfile
- scripts/update_smilecdr.sh
Closes #62 
Will rebase after #63 merges.
> 🐳 Push new Smile CDR releases to ECR + Dockerhub

- README.md
- scripts/clean.sh
- scripts/run_local_server.sh
Fix the path to the `dev.env` env var example file
Add accurate wait time to wait message in run_local_server.sh 
Rm change dir in clean.sh
> 🐛Fix README and scripts

- Jenkinsfile
> 👷 Add Jenkinsfile

- .github/workflows/gh_release.yml
> 👷 Add GH workflow to automate releases

- CHANGELOG.md
- Emojis: 📝 x2, 🚚 x1, 🚧 x1, 👷 x4, ♻️ x1, 🐛 x5, 🔧 x5, 🐳 x5, ⚡️ x1
- Categories: Documentation x2, Other Changes x9, Ops x9, Fixes x5
- [#82](https://github.com/kids-first/kf-api-fhir-service/pull/82) - 📝 Update README, add logo + badges - [2b806732](https://github.com/kids-first/kf-api-fhir-service/commit/2b8067327db19de18b411903134145489c9997a8) by [znatty22](https://github.com/znatty22)
- [#79](https://github.com/kids-first/kf-api-fhir-service/pull/79) - 🚚 Rename env vars for DB - [175c0454](https://github.com/kids-first/kf-api-fhir-service/commit/175c04542d3618bc5e7bd9fa45c668b62699136e) by [znatty22](https://github.com/znatty22)
- [#76](https://github.com/kids-first/kf-api-fhir-service/pull/76) - 🚧 Remove model deploy step from CI due to #74 - …
> 🔖 Release 0.1.0

- scripts/users.py
- server/settings/users.example.json
Helper scripts to create/update Smile CDR users. This is temporary functionality until #19 is implemented.
> ♻️ Update user mgmt scripts

- CHANGELOG.md
- release_maker_cfg.json
- Emojis: ♻️ x1, ? x1
- Categories: Other Changes x2
- [#88](https://github.com/kids-first/kf-api-fhir-service/pull/88) -  S3 Script + Configurable Request Validation - [f5fc9c49](https://github.com/kids-first/kf-api-fhir-service/commit/f5fc9c49483e0f2a56765c9b4c2d9a01ff43940f) by [znatty22](https://github.com/znatty22)
- [#83](https://github.com/kids-first/kf-api-fhir-service/pull/83) - ♻️ Update user mgmt scripts - [04a661d7](https://github.com/kids-first/kf-api-fhir-service/commit/04a661d7204f88f71d20dbfe587af3b04cf7a9f6) by [znatty22](https://github.com/znatty22)
> 🏷 Release 0.2.0

- README.md
- scripts/users.py
- server/settings/anonymous-user.json
> ✨ Grant anonymous user FHIR client superuser role

- CHANGELOG.md
- Emojis: ✨ x1
- Categories: Additions x1
- [#90](https://github.com/kids-first/kf-api-fhir-service/pull/90) - ✨ Grant anonymous user FHIR client superuser role - [16004177](https://github.com/kids-first/kf-api-fhir-service/commit/16004177a074ffff60ce362186c86a34ab0286b9) by [znatty22](https://github.com/znatty22)
> 🏷 Release 0.3.0

- docker-compose.yml
> 🐛 Add missing dashboard init env vars

- CHANGELOG.md
- Emojis: 👷 x1, 🐛 x1
- Categories: Ops x1, Fixes x1
- [#97](https://github.com/kids-first/kf-api-fhir-service/pull/97) - 👷 Migrate to kf-strides account - [de1edbcb](https://github.com/kids-first/kf-api-fhir-service/commit/de1edbcb60b55786a4e00f7f738989e4812be303) by [blackdenc](https://github.com/blackdenc)
- [#94](https://github.com/kids-first/kf-api-fhir-service/pull/94) - 🐛 Add missing dashboard init env vars - [19cc73b1](https://github.com/kids-first/kf-api-fhir-service/commit/19cc73b1bee1a719da3a6dde29a1f1e574d9ef9a) by [znatty22](https://github.com/znatty22)
> 🏷 Release 0.3.1

- .github/workflows/gh_release.yml
This is the current version of the release maker file
> 👷 Tag latest during release

- CHANGELOG.md
- Emojis: ? x2, ⬆️ x1, 🎉 x1, 🔧 x1, 👷 x1
- Categories: Additions x1, Ops x2, Other Changes x3
- [#106](https://github.com/kids-first/kf-api-fhir-service/pull/106) -  Feature/add caring - [b7c7580a](https://github.com/kids-first/kf-api-fhir-service/commit/b7c7580a24873cf9d3f2d669814c8b6a21cd6868) by [alubneuski](https://github.com/alubneuski)
- [#105](https://github.com/kids-first/kf-api-fhir-service/pull/105) - ⬆️ Upgrade to 2021.02.R05 - [c17097cf](https://github.com/kids-first/kf-api-fhir-service/commit/c17097cf48013982124b38e6584d83f384080a01) by [liberaliscomputing](https://github.com/liberaliscomputing)
- [#104](https://github.com/kids-first/kf-api-fhir-service/pull/104) - 🎉 Added Jenkinsfile for CARING - [4f87169a](https://github.com/kids-first/kf-api-fhir-service/commit/4f87169a42849 …
> 🏷 Release 0.4.0

- Jenkinsfile_CLOVoc
This PR add a Jenkinsfile for CLOVoc FHIR DEV.
> 🔧  Add CLOVoc

- Jenkinsfile_CLOVoc
> :wrench: Updated healthcheck path

- Jenkinsfile
Description
=========
Added service discovery for FHIR server container.
> :wrench: Added service discovery

- Jenkinsfile
Added security group for EMR cluster
> 🔒 Added security group

- .github/workflows/local_integration_test.yml
- .gitignore
- src/bin/health-check.sh
- src/bin/load_data.py
- test/test.sh
Closes #134 
We need to ensure the server settings were correctly applied to the container and that users with appropriate permissions can take expected actions.
- Add a github workflow for integration testing against a docker-compose stack
- Run quickstart steps to test that data can be created, users can be seeded
- Test that CRUD operations work on server (use quickstart.sh)
- Test that basic auth works and users must be assigned roles to do anything (add curl step to workflow)
- Test that anonymous user can only GET `/metadata` (add curl step to workflow)
- (Later) Will add a real test suite with unit tests and integration tests to cover all CRUD functionality
> ✅ Initial integration test

- README.md
- smilecdr/settings/auth.js
**Note** The README mentions all three deployments, but the upgraded FHIR service has only been deployed to the dev environment. The other deployments are coming soon
Closes #136
Closes #140
> 📝 Rewrite README for major upgrade

- smilecdr/settings/auth.js
- tests/javascript/auth.test.js
- Add documentation
- Add missing test
> ♻️ Improve auth.js

- CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#168](https://github.com/kids-first/kf-api-fhir-service/pull/168) - 🐛 Add PRD keycloak server to config - [a4fc20f6](https://github.com/kids-first/kf-api-fhir-service/commit/a4fc20f668996f63a4816d47d95f99ab71b88069) by [znatty22](https://github.com/znatty22)
> 🏷 Release 1.0.1

- CHANGELOG.md
- Emojis: ? x1
- Categories: Other Changes x1
- [#170](https://github.com/kids-first/kf-api-fhir-service/pull/170) -  :bug: Fix prd OIDC issuer url - [a2ad17bb](https://github.com/kids-first/kf-api-fhir-service/commit/a2ad17bb8162071d384e974209a1ae816ce2ffcd) by [znatty22](https://github.com/znatty22)
> 🏷 Release 1.0.2

- Dockerfile.includedcc
- Dockerfile.kidsfirst-upgrade
- README.md
- bin/upgrade/new_image.sh
- bin/upgrade/upgrade_dockherhub_image.sh
- bin/upgrade/upgrade_ecr_image.sh
- bin/upgrade_dockherhub_image.sh
- dev-requirements.txt
- docker-compose.yml
- src/bin/load_data.py
- src/bin/quickstart.sh
Smile CDR / HAPI fixed a couple of critical bugs:
- Previously could not use async loading to update data on server
- Previously could not use audit DB with OIDC
- Pushed new image to kidsfirstdrc/smilecdr on Dockerhub
- Updated docker-compose to use new image on Dockerhub
- Updated kf and include Dockerfiles to use new image
- (Todo) Push new image kf-strides and includedcc ECRs (@alubneuski)
> ⬆️ Upgrade to version 2023.05.R02

- smilecdr/settings/oidc-servers.json
> :wrench: Change PRD Keycloak URL to new one
